[package]
name = "model_btc"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"
